export const ADD_QUESTION = "ADD_QUESTION";
export const UPDATE_TITLE = "UPDATE_TITLE";
export const UPDATE_DESC = "UPDATE_DESC";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_OPTIONS = "UPDATE_OPTIONS";
